#! /bin/sh
### BEGIN INIT INFO
# Provides:          mjpg-streamer
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Autostart webcam stream for robot software
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin:/home/ubuntu/widgets:/usr/local/bin

case "$1" in
    start)
	mjpg_streamer -i "/usr/lib/input_uvc.so -r 320x240 -f 5" -o "/usr/lib/output_http.so -p 8090"
	;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
