#! /bin/sh
### BEGIN INIT INFO
# Provides:          robot
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Autostart the Ansync robot software
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin:/home/ubuntu/widgets:/usr/local/bin

case "$1" in
    start)
	nodemon /home/ubuntu/widgets/app.js
	;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
